# cloudbuild.yaml
steps:
  - name: node:12.14.1
    entrypoint: yarn
    args: ["install"]
  - name: node:12.14.1
    entrypoint: yarn
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
